import React, { useState, useEffect } from 'react';
import { X, FileDown, FileText, Check, Printer } from 'lucide-react';
import { ResearchSession } from '../types';

interface ExportModalProps {
  isOpen: boolean;
  onClose: () => void;
  session: ResearchSession;
}

export const ExportModal: React.FC<ExportModalProps> = ({ isOpen, onClose, session }) => {
  const [downloaded, setDownloaded] = useState<'md' | 'pdf' | null>(null);

  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      if (e.key === 'Escape') onClose();
    };
    if (isOpen) window.addEventListener('keydown', handleKeyDown);
    return () => window.removeEventListener('keydown', handleKeyDown);
  }, [isOpen, onClose]);

  if (!isOpen) return null;

  const generateMarkdownContent = () => {
    let md = `# Deep Research Report: ${session.topic}\n\n`;
    md += `*Generated by AI Deep Researcher on ${new Date(session.createdAt).toLocaleDateString()}*\n\n`;
    md += `---\n\n`;

    if (session.summary) {
      md += `## Executive Briefing\n\n${session.summary.executiveSummary}\n\n`;

      if (session.summary.takeaways?.length) {
        md += `### Key Strategic Takeaways\n\n`;
        session.summary.takeaways.forEach((t) => {
          md += `- ${t}\n`;
        });
        md += `\n`;
      }

      session.summary.detailedSections.forEach((sec) => {
        md += `### ${sec.heading}\n\n${sec.content}\n\n`;
      });

      md += `### Plain Language Summary (ELI5)\n\n${session.summary.summary_basic}\n\n`;
    }

    if (session.analysis) {
      md += `## Trend & Subtopic Momentum\n\n`;
      md += `| Subtopic | Momentum Score | Sentiment | Stage |\n`;
      md += `|---|---|---|---|\n`;
      session.analysis.subtopics.forEach((s) => {
        md += `| ${s.name} | ${s.momentumScore}/100 | ${s.sentiment} | ${s.stage} |\n`;
      });
      md += `\n`;

      if (session.analysis.emergingThemes?.length) {
        md += `**Emerging Themes:** ${session.analysis.emergingThemes.join(', ')}\n\n`;
      }
      if (session.analysis.decliningThemes?.length) {
        md += `**Declining Themes:** ${session.analysis.decliningThemes.join(', ')}\n\n`;
      }
    }

    md += `## Sources Analyzed (${session.sources.length})\n\n`;
    session.sources.forEach((s, idx) => {
      md += `${idx + 1}. **[${s.title}](${s.url})** - *${s.domain}* (${s.credibilityType})\n`;
      md += `   > ${s.snippet}\n\n`;
    });

    if (session.relatedUrls?.length) {
      md += `## Miscellaneous Outbound Links Discovered (${session.relatedUrls.length})\n\n`;
      session.relatedUrls.forEach((r, idx) => {
        md += `- [${r.title || r.domain}](${r.url}) (*${r.domain}*)\n`;
      });
      md += `\n`;
    }

    return md;
  };

  const handleDownloadMarkdown = () => {
    const content = generateMarkdownContent();
    const blob = new Blob([content], { type: 'text/markdown;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `research-${session.topic.toLowerCase().replace(/[^a-z0-9]/g, '-')}.md`;
    link.click();
    URL.revokeObjectURL(url);
    setDownloaded('md');
    setTimeout(() => setDownloaded(null), 2000);
  };

  const handlePrintPdf = () => {
    window.print();
    setDownloaded('pdf');
    setTimeout(() => setDownloaded(null), 2000);
  };

  return (
    <div
      onClick={onClose}
      className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-paper-text/40 backdrop-blur-xs animate-in fade-in"
    >
      <div
        onClick={(e) => e.stopPropagation()}
        className="bg-paper-surface w-full max-w-md rounded-2xl border border-paper-line shadow-paper-lg p-6 space-y-4"
      >
        <div className="flex items-center justify-between pb-3 border-b border-paper-line">
          <div className="flex items-center space-x-2">
            <FileDown className="w-5 h-5 text-terracotta" />
            <h4 className="font-serif font-bold text-lg text-paper-text">Export Research Report</h4>
          </div>
          <button
            type="button"
            onClick={onClose}
            className="p-1.5 rounded-lg hover:bg-paper-surface-2 transition cursor-pointer"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        <p className="text-xs text-paper-text-dim">
          Export the complete research dossier on <strong>&ldquo;{session.topic}&rdquo;</strong> including executive briefings, trend analyses, and full citations.
        </p>

        <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 pt-2">
          {/* Markdown Download */}
          <button
            onClick={handleDownloadMarkdown}
            className="flex flex-col items-center justify-center p-5 bg-paper-surface-2/60 hover:bg-paper-surface-2 rounded-xl border border-paper-line hover:border-terracotta transition space-y-2 group"
          >
            {downloaded === 'md' ? (
              <Check className="w-6 h-6 text-sage" />
            ) : (
              <FileText className="w-6 h-6 text-terracotta group-hover:scale-105 transition" />
            )}
            <span className="font-medium text-xs text-paper-text">Markdown (.md)</span>
            <span className="text-[10px] text-paper-text-dim text-center">Complete formatted dossier</span>
          </button>

          {/* PDF Print View */}
          <button
            onClick={handlePrintPdf}
            className="flex flex-col items-center justify-center p-5 bg-paper-surface-2/60 hover:bg-paper-surface-2 rounded-xl border border-paper-line hover:border-terracotta transition space-y-2 group"
          >
            {downloaded === 'pdf' ? (
              <Check className="w-6 h-6 text-sage" />
            ) : (
              <Printer className="w-6 h-6 text-dusty group-hover:scale-105 transition" />
            )}
            <span className="font-medium text-xs text-paper-text">Print / PDF</span>
            <span className="text-[10px] text-paper-text-dim text-center">Print-ready editorial paper</span>
          </button>
        </div>

        <div className="pt-3 text-right">
          <button
            onClick={onClose}
            className="px-4 py-2 rounded-lg bg-paper-surface-2 border border-paper-line text-xs font-medium text-paper-text hover:bg-paper-line"
          >
            Close
          </button>
        </div>
      </div>
    </div>
  );
};
